### ISSUE TITLE
OnLineStore

### ISSUE THREAD

**Issue by ewmccarty** [hherzl/CatFactory#3]
Where is the source for the OnLineStore database?

**Comment by hherzl** [comment]
Hi.

Do you mean scripts for OnLineStore database?

Check this link: [Scripts](https://github.com/hherzl/EntityFrameworkCore2ForEnterprise/tree/master/Resources/Database)

Let me know if this is useful.

Regards

**Comment by ewmccarty** [comment]
That was what I needed.... thanks.
