### ISSUE TITLE
Could I contact to U

### ISSUE THREAD

**Issue by Diaskhan** [hherzl/CatFactory#6]
It is possible to contact to U ?
I have Idea about ef core!

Developing custom migrator uppon Ef core Migration tools!
Already possible to generate Migrations and apply it!
But need Yore opinon!

It very Enterprise Idea !
Have build js gui on vue!

![image](https://user-images.githubusercontent.com/15046677/55977736-5960e580-5cb1-11e9-85b2-43991813493d.png)

**Comment by hherzl** [comment]
Hi.

Yes, do you have linked in?

**Comment by Diaskhan** [comment]
My mail diaskhan@yanddex.kz 
Write me !

**Comment by Diaskhan** [comment]
I have entity model definition that compiles model to assembly.
Then assembly is loading.
And then ientityconfigurations applyes to current dbcontext! 

After all dbcontext usses imigrationdiffer 
Like described in this topic 
https://stackoverflow.com/questions/49946019/how-can-i-use-the-entity-framework-core-capabilities-to-change-my-database

After all database structure is actual wih new types !

**Comment by hherzl** [comment]
Hi, I have wrote to diaskhan@yanddex.kz address, but it was failed.

Can you confirm your contact please?

**Comment by Diaskhan** [comment]
Sorry. Diaskhan@yandex.kz

**Comment by hherzl** [comment]
(y)
